[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]

normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"

size = 15.0
