[window]
blur = true
opacity = 0.85

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

option_as_alt = "Both"

[selection]
save_to_clipboard = true

[font]

normal.family = "Hack Nerd Font Mono"
bold.family = "Hack Nerd Font Mono"
italic.family = "Hack Nerd Font Mono"
bold_italic.family = "Hack Nerd Font Mono"

size = 15.0

[keyboard]
bindings = [
  # Disable Cmd-W and Cmd-Q to prevent accidental exit
  { key = "Q", mods = "Command", action = "None" }, # not working
  { key = "W", mods = "Command", action = "None" },
  # { key = "Backspace", mods = "Control", chars = "\u0008" },
  { key = "Backspace", mods = "Control", chars = "\u0017" },
  # { key = "W", mods = "Control", chars = "\u0008" }

  # On macos: you might need to disable the ctrl left and right bindings from mission control
  # ref: https://stackoverflow.com/a/72995176/2514803
  { key = "Left",  mods = "Control", chars = "\u001B[1;5D" },
  { key = "Right", mods = "Control", chars = "\u001B[1;5C" },
]
